version: '3.8'

services:
  app:
    build: .
    ports:
      - "3001:3001"  # Updated both ports to 3001
    environment:
      - PORT=3001    # Added explicit PORT environment variable
      - MONGODB_URI=mongodb://mongodb:27017/emailonebox
      - ELASTICSEARCH_NODE=http://elasticsearch:9200
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SLACK_WEBHOOK_URL=${SLACK_WEBHOOK_URL}
    depends_on:
      - mongodb
      - elasticsearch

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

volumes:
  mongodb_data:
  elasticsearch_data: